// This file is auto-generated by SoundManager. Do not modify manually.
namespace HornDancheong.Audio
{
    public enum SFXType
    {
        None = 0,
        premswaroopkasukurthi_hit_sound_effect_12445 = 1,
    }
}
