using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace HornDancheong.Audio
{
    /// <summary>
    /// SoundManager 인스펙터 커스텀 에디터 툴입니다.
    /// 설정된 BGM 및 SFX 폴더 내부의 AudioClip 애셋들을 스캔하고,
    /// 각각에 대응하는 BGMType 및 SFXType Enum 스크립트를 동적으로 자동 생성합니다.
    /// </summary>
    [CustomEditor(typeof(SoundManager))]
    public class SoundManagerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            // 기본 인스펙터 표시
            DrawDefaultInspector();

            SoundManager manager = (SoundManager)target;

            EditorGUILayout.Space(15);
            EditorGUILayout.LabelField("▼ [SW] 사운드 매니저 폴더 동기화 및 Enum 생성 도구", EditorStyles.boldLabel);

            if (GUILayout.Button("오디오 폴더 스캔 및 Enum 생성 (Scan & Generate)", GUILayout.Height(35)))
            {
                ScanAndGenerate(manager);
            }
        }

        private void ScanAndGenerate(SoundManager manager)
        {
            // 1. SFX 스캔 및 리스트 업데이트
            List<AudioClip> sfxClips = ScanFolderForClips(manager.SfxFolderPath);

            // 2. BGM 스캔 및 리스트 업데이트
            List<AudioClip> bgmClips = ScanFolderForClips(manager.BgmFolderPath);

            // 3. SerializedProperty를 사용하여 안전하게 리스트 동기화
            serializedObject.Update();

            SerializedProperty sfxProp = serializedObject.FindProperty("sfxClips");
            sfxProp.ClearArray();
            for (int i = 0; i < sfxClips.Count; i++)
            {
                sfxProp.InsertArrayElementAtIndex(i);
                sfxProp.GetArrayElementAtIndex(i).objectReferenceValue = sfxClips[i];
            }

            SerializedProperty bgmProp = serializedObject.FindProperty("bgmClips");
            bgmProp.ClearArray();
            for (int i = 0; i < bgmClips.Count; i++)
            {
                bgmProp.InsertArrayElementAtIndex(i);
                bgmProp.GetArrayElementAtIndex(i).objectReferenceValue = bgmClips[i];
            }

            serializedObject.ApplyModifiedProperties();

            // 4. SFXType.cs 생성
            string sfxEnumPath = "Assets/1.Scripts/SW/Audio/SFXType.cs";
            GenerateEnumFile("SFXType", sfxClips, sfxEnumPath);

            // 5. BGMType.cs 생성
            string bgmEnumPath = "Assets/1.Scripts/SW/Audio/BGMType.cs";
            GenerateEnumFile("BGMType", bgmClips, bgmEnumPath);

            // 6. 변경 사항 저장 및 컴파일 갱신
            EditorUtility.SetDirty(manager);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[SoundManagerEditor] 폴더 동기화 및 Enum 생성 완료! (SFX: {sfxClips.Count}개, BGM: {bgmClips.Count}개)");
        }

        private List<AudioClip> ScanFolderForClips(string relativePath)
        {
            List<AudioClip> clips = new List<AudioClip>();

            if (string.IsNullOrEmpty(relativePath))
            {
                Debug.LogWarning("[SoundManagerEditor] 폴더 경로가 비어 있습니다.");
                return clips;
            }

            if (!Directory.Exists(relativePath))
            {
                Debug.LogWarning($"[SoundManagerEditor] 폴더가 파일 시스템에 존재하지 않습니다: {relativePath}");
                return clips;
            }

            // 폴더 내 오디오 클립 탐색 (FindAssets)
            string[] guids = AssetDatabase.FindAssets("t:AudioClip", new[] { relativePath });

            foreach (string guid in guids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                
                // 만약 지정된 폴더의 직계 자식이 아니거나 다른 경로에 속한 파일도 탐색되는 것을 대비하여 검사
                // (일부 유니티 FindAssets의 동작을 제한하기 위해 하위 폴더에 있는 것만 허용)
                AudioClip clip = AssetDatabase.LoadAssetAtPath<AudioClip>(assetPath);
                if (clip != null && !clips.Contains(clip))
                {
                    clips.Add(clip);
                }
            }

            // 정렬해서 Enum 순서 보정
            clips.Sort((a, b) => string.Compare(a.name, b.name, System.StringComparison.Ordinal));

            return clips;
        }

        private void GenerateEnumFile(string enumName, List<AudioClip> clips, string savePath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// This file is auto-generated by SoundManager. Do not modify manually.");
            sb.AppendLine("namespace HornDancheong.Audio");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");

            int index = 1;
            HashSet<string> addedNames = new HashSet<string>();

            foreach (var clip in clips)
            {
                if (clip == null) continue;
                string sanitized = SoundManager.SanitizeName(clip.name);
                if (sanitized == "None") continue;

                if (addedNames.Add(sanitized))
                {
                    sb.AppendLine($"        {sanitized} = {index},");
                    index++;
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 디렉토리 존재 확인 및 생성
            string directory = Path.GetDirectoryName(savePath);
            if (directory != null && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(savePath, sb.ToString(), Encoding.UTF8);
        }
    }
}
